Repository modern-agile-team/8term-coko-Front, pull requests merged in 2024-10, with the labels that each got.

#36 ghcr 로그인 UserName 수정
  .github/workflows/ci-cd.yml
Labels: 🐞 BugFix

#40 탠스택쿼리, 개발도구 및 라우터 분리
  package-lock.json
  package.json
  src/App.tsx
  src/route/Router.tsx
Labels: ⚙ Setting, 📝 Modify

#44 어드민 페이지 퍼블리싱 완성했습니다
  src/admin/Admin.tsx
  src/admin/CreateQuiz.tsx
  src/admin/style.ts
  src/admin/types/Quiz.ts
  src/admin/types/style.ts
  src/route/Router.tsx
Labels: 🎨 Publish

#45 퀴즈페이지 레이아웃 완성
  src/features/Quiz/styles.ts
  src/features/Quiz/ui/Button.tsx
  src/features/Quiz/ui/Combination.tsx
  src/features/Quiz/ui/MultipleChoice.tsx
  src/features/Quiz/ui/OXSelector.tsx
  src/features/Quiz/ui/Question.tsx
  src/features/Quiz/ui/ShortAnswer.tsx
  src/pages/Quiz/Quiz.tsx
  src/pages/Quiz/styles.ts
  src/route/Router.tsx
  src/store/useQuizStore.tsx
  src/types/Quiz.ts
  src/utils/componentMap.tsx
Labels: 🎨 Publish

#48 Vite @swc/plugin-styled-components 적용
  package-lock.json
  package.json
  vite.config.ts
Labels: ⚙ Setting

#51 악시오스 세팅 + 리액트 쿼리 테스트 api 구축
  .gitignore
  src/admin/types/Quiz.ts
  src/apis/axios/instance.ts
  src/apis/axios/intercepter.ts
  src/apis/axios/statusCode.ts
  src/apis/quiz.ts
Labels: 📬 API

#53 어드민 페이지 기능구현
  src/admin/Admin.tsx
  src/admin/CreateQuiz.tsx
  src/admin/types/Quiz.ts
  src/apis/quiz.ts
Labels: ✨ Feature

#55 로그인(Oauth) 페이지 레이아웃 완성
  src/pages/login/Login.tsx
  src/pages/login/styles.ts
  src/route/Router.tsx
Labels: 🎨 Publish

#57 어드민 폴더 제거
  src/admin/Admin.tsx
  src/admin/CreateQuiz.tsx
  src/admin/style.ts
  src/admin/types/Quiz.ts
  src/admin/types/style.ts
  src/apis/quiz.ts
  src/route/Router.tsx
  src/types/Quiz.ts
Labels: 🔨 Refactor
