Repository modern-agile-team/8term-coko-Front, pull requests merged in 2024-11, with the labels that each got.

#59 quiz기능 완성
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/ModalPortal.tsx
  src/apis/axios/instance.ts
  src/apis/axios/intercepter.ts
  src/apis/quiz.ts
  src/apis/quizzesApis.ts
  src/apis/usersApis.ts
  src/common/layout/Modal.tsx
  src/common/layout/style.ts
  src/features/Quiz/ui/Button.tsx
  src/features/Quiz/ui/Combination.tsx
  src/features/Quiz/ui/MultipleChoice.tsx
  src/features/Quiz/ui/OXSelector.tsx
  src/features/Quiz/ui/Question.tsx
  src/features/Quiz/ui/ShortAnswer.tsx
  src/features/quiz/service/emptyChangeToDiv.ts
  src/features/quiz/service/lineChanger.ts
  src/features/quiz/styles.css
  src/features/quiz/styles.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/OXSelector.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/ResultModal.tsx
  src/features/quiz/ui/ShortAnswer.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/hooks/useBeforeUnload.ts
  src/hooks/useModal.ts
  src/hooks/usePreservedCallback.ts
  src/pages/Quiz/Quiz.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/styles.ts
  src/queries/quizzesQuery.ts
  src/queries/usersQuery.ts
  src/route/Router.tsx
  src/store/useClientQuizStore.ts
  src/store/useQuizStore.tsx
  src/store/useUserStore.ts
  src/types/Quiz.ts
  src/types/User.ts
  src/utils/compact.ts
  src/utils/componentMap.tsx
  src/utils/getParams.ts
  src/utils/isEqualArray.ts
  src/utils/noop.ts
Labels: ✨ Feature

#61 Styled-components의 글로벌 스타일 및 미디어(반응형) 적용
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/pages/learn/Learn.tsx
  src/route/Router.tsx
  src/style/GlobalStyle.ts
  src/style/index.css
  src/style/media.ts
Labels: ⚙ Setting

#62 퀴즈페이지 퍼블리싱
  src/features/quiz/styles.css
  src/features/quiz/styles.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/OXSelector.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/ShortAnswer.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/hooks/useModal.ts
  src/hooks/usePreloadImages.ts
  src/pages/quest/Quest.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/styles.ts
  src/pages/ranking/Ranking.tsx
  src/store/useClientQuizStore.ts
  src/style/LayOut.ts
  src/utils/handlePage.ts
Labels: 🎨 Publish

#64 함수 수정, P테그 중첩 수정, usePreloadImage 에러메세지 수정
  src/features/quiz/styles.ts
  src/features/quiz/ui/TotalResults.tsx
  src/hooks/usePreloadImages.ts
  src/utils/handlePage.ts
Labels: 🐞 BugFix

#66 메인페이지 퍼블리싱
  package-lock.json
  package.json
  src/common/layout/CokoLogo.tsx
  src/common/layout/Header.tsx
  src/common/layout/MenuBar.tsx
  src/common/layout/Modal.tsx
  src/common/layout/style.ts
  src/common/style/.gitkeep
  src/common/ui/.gitkeep
  src/common/ui/HeaderItem.tsx
  src/common/ui/MenuItem.tsx
  src/common/ui/style.ts
  src/features/Learn/service/getPartGridPosition.ts
  src/features/Learn/style.ts
  src/features/Learn/ui/KeycapAdventureIntro.tsx
  src/features/Learn/ui/SectionArrowButton.tsx
  src/features/Learn/ui/SectionNavigateContainer.tsx
  src/features/Learn/ui/SelectSection.tsx
  src/features/Progress/style.ts
  src/features/Progress/ui/ProgressBar.tsx
  src/features/Quest/style.ts
  src/features/Quest/ui/DailyQuest.tsx
  src/features/Quest/ui/MainQuest.tsx
  src/features/Quiz/ui/PartNavContainer.tsx
  src/features/Quiz/ui/QuizSection.tsx
  src/features/quiz/service/lineChanger.ts
  src/features/quiz/styles.ts
  src/features/quiz/ui/Result.tsx
  src/hooks/useBeforeUnload.ts
  src/hooks/usePreloadImages.ts
  src/hooks/usePreservedCallback.ts
  src/hooks/useScrollVisibility.ts
  src/pages/Quest/Quest.tsx
  src/pages/Ranking/Ranking.tsx
  src/pages/learn/Learn.tsx
  src/pages/learn/style.ts
  src/pages/quest/Quest.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/styles.ts
  src/pages/ranking/Ranking.tsx
  src/style/LayOut.ts
  src/style/style.ts
  src/utils/getImageUrl.ts
  src/utils/noop.ts
Labels: 🎨 Publish

#69 폴더 대소문자 오류 수정
  src/features/learn/service/getPartGridPosition.ts
  src/features/learn/style.ts
  src/features/learn/ui/KeycapAdventureIntro.tsx
  src/features/learn/ui/SectionArrowButton.tsx
  src/features/learn/ui/SectionNavigateContainer.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/progress/style.ts
  src/features/progress/ui/ProgressBar.tsx
  src/features/quest/style.ts
  src/features/quest/ui/DailyQuest.tsx
  src/features/quest/ui/MainQuset.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/QuizSection.tsx
  src/pages/Quest/Quest.tsx
  src/pages/Ranking/Ranking.tsx
  src/pages/learn/Learn.tsx
  src/pages/learn/style.ts
  src/pages/quest/Quest.tsx
Labels: 🐞 BugFix

#74 절대경로 설정 완료
  package-lock.json
  package.json
  src/features/quiz/ui/TotalResults.tsx
  tsconfig.app.json
  vite.config.ts
Labels: ⚙ Setting

#71 유저 경험치 지급 로직 완성
  src/apis/quizzesApis.ts
  src/apis/usersApis.ts
  src/features/quiz/styles.ts
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/pages/quiz/Quiz.tsx
  src/queries/quizzesQuery.ts
  src/queries/usersQuery.ts
  src/store/useClientQuizStore.ts
  src/store/useUserStore.ts
  src/types/Experience.ts
  src/types/User.ts
  src/utils/getParams.ts
Labels: ✨ Feature

#75 퀴즈 진행도 구현
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/styles.ts
  tsconfig.app.json
Labels: ✨ Feature
