Repository modern-agile-team/8term-coko-Front, pull requests merged in 2024-12, with the labels that each got.

#80 인가/비인가 유저별 문제 유형 처리
  index.html
  package-lock.json
  package.json
  public/favicon.svg
  src/apis/axios/intercepter.ts
  src/apis/usersApis.ts
  src/common/layout/CokoLogo.tsx
  src/common/layout/Header.tsx
  src/common/layout/style.ts
  src/common/ui/HeaderItem.tsx
  src/common/ui/style.ts
  src/features/login/service/.gitkeep
  src/features/login/service/handleSocialLogin.ts
  src/features/login/style/.gitkeep
  src/features/login/styles.ts
  src/features/login/ui/.gitkeep
  src/features/login/ui/Login.tsx
  src/features/login/ui/LoginPrompt.tsx
  src/features/quiz/styles.ts
  src/features/quiz/ui/PartClear.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/hooks/useFunnel.tsx
  src/hooks/useModal.ts
  src/hooks/useOutsideClick.ts
  src/main.tsx
  src/pages/learn/Learn.tsx
  src/pages/login/Login.tsx
  src/pages/login/styles.ts
  src/pages/quiz/Quiz.tsx
  src/queries/quizzesQuery.ts
  src/queries/usersQuery.ts
  src/route/Router.tsx
  src/style/LayOut.ts
  src/utils/cookie.ts
  vite.config.ts
Labels: ✨ Feature, 🔨 Refactor

#82 프로필 페이지
  src/features/user/styles.ts
  src/features/user/ui/BadgeContainer.tsx
  src/features/user/ui/ProfileImage.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/styles.ts
  src/route/Router.tsx
Labels: 🎨 Publish

#84 상점 페이지 퍼블리싱
  src/features/store/ui/CartList.tsx
  src/features/store/ui/ItemContainer.tsx
  src/features/store/ui/StoreItem.tsx
  src/features/store/ui/styles.ts
  src/features/user/ui/BadgeContainer.tsx
  src/features/user/ui/MyCharacter.tsx
  src/features/user/ui/styles.ts
  src/pages/store/Store.tsx
  src/pages/store/styles.ts
  src/route/Router.tsx
  src/types/CosmeticItem .ts
Labels: 🎨 Publish

#86 oAuth, 로그인 유무 로직 구현
  .github/workflows/ci-cd.yml
  index.html
  src/apis/axios/intercepter.ts
  src/apis/axios/interceptor.ts
  src/common/layout/Header.tsx
  src/common/layout/style.ts
  src/common/ui/style.ts
  src/features/login/service/handleLogin.ts
  src/features/login/service/handleLogout.ts
  src/features/login/service/handleSocialLogin.ts
  src/features/login/styles.ts
  src/features/login/ui/Login.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/hooks/useOutsideClick.ts
  src/hooks/usePopover.ts
  src/pages/learn/Learn.tsx
  src/utils/cookies.ts
  src/utils/isLoggedIn.ts
Labels: ✨ Feature

#90 하이라이팅+드레그엔드롭 구현
  package-lock.json
  package.json
  src/common/layout/Header.tsx
  src/common/layout/Modal.tsx
  src/features/quiz/service/addLineNumbersToCode.ts
  src/features/quiz/service/emptyChangeToDiv.ts
  src/features/quiz/service/lineChanger.ts
  src/features/quiz/service/replaceEmptyWithHTMLElement.ts
  src/features/quiz/service/useCodeHighlight.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/OXSelector.tsx
  src/features/quiz/ui/PartClear.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/QuizSection.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/ShortAnswer.tsx
  src/features/quiz/ui/TextBlock.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/features/quiz/ui/styles.css
  src/features/quiz/ui/styles.ts
  src/features/user/ui/MyCharacter.tsx
  src/features/user/ui/ProfileImage.tsx
  src/features/user/ui/styles.ts
  src/pages/quiz/Quiz.tsx
  src/store/useClientQuizStore.ts
  src/store/useDnDStore.ts
Labels: ✨ Feature

#93 프롭스 전달 수정
  src/pages/profile/Profile.tsx
  src/pages/store/Store.tsx
Labels: 🐞 BugFix

#94 랭킹 페이지
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/axios/instance.ts
  src/axios/interceptor.ts
  src/axios/statusCode.ts
  src/features/.gitkeep
  src/features/quiz/apis.ts
  src/features/quiz/queries.ts
  src/features/quiz/types.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/PartClear.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/features/quiz/ui/styles.ts
  src/features/ranking/constant.ts
  src/features/ranking/ui/MyRank.tsx
  src/features/ranking/ui/RankingContainer.tsx
  src/features/ranking/ui/SortDropdown.tsx
  src/features/ranking/ui/styles.ts
  src/features/store/types.ts
  src/features/store/ui/CartList.tsx
  src/features/store/ui/ItemContainer.tsx
  src/features/store/ui/StoreItem.tsx
  src/features/store/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/types.ts
  src/pages/.gitkeep
  src/pages/learn/Learn.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/ranking/Ranking.tsx
  src/pages/ranking/styles.ts
  src/pages/store/Store.tsx
  src/store/useUserStore.ts
  src/types/.gitkeep
  src/types/Experience.ts
  src/types/User.ts
  tsconfig.app.json
Labels: 🎨 Publish

#95 퀴즈 반응형 페이지 작업
  src/common/layout/style.ts
  src/features/quiz/ui/PartClear.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/TotalResults.tsx
  src/features/quiz/ui/styles.ts
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/styles.ts
Labels: 🎨 Publish
