Repository modern-agile-team/8term-coko-Front, pull requests merged in 2024-09, with the labels that each got.

#20 폴더구조 약간 변경 + common 폴더 생성
  src/common/layout/.gitkeep
  src/common/style/.gitkeep
  src/common/ui/.gitkeep
  src/features/.gitkeep
  src/features/login/service/.gitkeep
  src/features/login/style/.gitkeep
  src/features/login/ui/.gitkeep
Labels: ⚙ Setting

#21 issue-branch.yml commentMessage 수정
  .github/issue-branch.yml
Labels: ⚙ Setting

#23 메인페이지 그리드 시스템 생성
  index.html
  src/App.tsx
  src/main.tsx
  src/pages/main/Main.tsx
  src/pages/main/style.ts
  src/pages/main/type.ts
  src/style/gridSystem.ts
Labels: 🎨 Publish

#25 Github Actions/Docker/EC2를 활용한 배포 자동화(CI/CD) 구축
  .dockerignore
  Dockerfile
  README.md
  vite.config.ts
Labels: ⚙ Setting

#27 🐞 BugFix(#26): GitHub Repository 로그인
  .github/workflows/ci-cd.yml
Labels: 🐞 BugFix

#29 Vite 기본 PORT 변경
  Dockerfile
  vite.config.ts
Labels: ⚙ Setting
