Repository modern-agile-team/8term-coko-Front, pull requests merged in 2025-02, with the labels that each got.

#125 404페이지 퍼블리싱
  src/features/error/ui/NotFound.tsx
  src/features/error/ui/styles.ts
Labels: 🎨 Publish

#129 퀴즈 로직 버그수정
  src/features/quiz/hocs/withQuizzes.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/QuizContainer.tsx
Labels: 🐞 BugFix

#126 Section 무한스크롤 구현 및 User 문제 풀이 현황 조회
  package-lock.json
  src/features/error/ui/HeaderErrorBoundary.tsx
  src/features/error/ui/styles.ts
  src/features/learn/apis.ts
  src/features/learn/constants.ts
  src/features/learn/hocs/withSections.tsx
  src/features/learn/hocs/withUserProgress.tsx
  src/features/learn/queries.ts
  src/features/learn/types.ts
  src/features/learn/ui/LearnContainer.tsx
  src/features/learn/ui/PartItem.tsx
  src/features/learn/ui/PartNavContainer.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/quiz/constants.ts
  src/features/quiz/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/types.ts
  src/hooks/useScrollVisibility.ts
  src/pages/learn/Learn.tsx
  src/pages/learn/styles.ts
Labels: ✨ Feature, 📬 API

#131 quiz 폴더 partNavContainer 파일 삭제
  src/features/learn/ui/PartItem.tsx
  src/features/learn/ui/PartNavContainer.tsx
  src/features/quiz/ui/PartNavContainer.tsx
Labels: 🐞 BugFix

#134 api, 쿼리 키 수정
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/ui/PartClear.tsx
  src/features/user/ui/TotalResults.tsx
Labels: 🐞 BugFix, 📝 Modify

#137 튜토리얼, 퀴즈 버그해결
  src/common/layout/Header.tsx
  src/common/layout/HeaderItemContainer.tsx
  src/common/layout/UserPresentHeaderItemContainer.tsx
  src/features/quiz/hooks.ts
  src/features/quiz/ui/QuizContainer.tsx
  src/features/quiz/ui/Result.tsx
  src/features/tutorial/service/hooks.ts
  src/features/tutorial/ui/TutorialContainer.tsx
  src/features/tutorial/ui/styles.ts
  src/features/user/queries.ts
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/tutorial/QuizTutorial.tsx
  src/style/animations.ts
Labels: 🐞 BugFix

#140 생명력 로직 버그수정
  src/features/learn/queries.ts
  src/features/quiz/hooks.ts
  src/features/quiz/ui/QuizContainer.tsx
  src/features/quiz/ui/Result.tsx
  src/features/user/hooks.ts
  src/features/user/queries.ts
  src/features/user/ui/PartClear.tsx
  src/features/user/ui/TotalResults.tsx
  src/pages/quiz/Quiz.tsx
  src/store/useClientQuizStore.ts
Labels: 🐞 BugFix

#138 출석체크 퍼블리싱 & 기능구현
  src/common/layout/HeaderItemContainer.tsx
  src/common/layout/Modal.tsx
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/service/utils.ts
  src/features/user/types.ts
  src/features/user/ui/AttendanceCalendar.tsx
  src/features/user/ui/AttendanceCalendarModal.tsx
  src/features/user/ui/styles.ts
Labels: ✨ Feature

#135 랭킹 페이지 기능 구현
  src/common/layout/Skeleton.tsx
  src/common/layout/styles.ts
  src/features/learn/ui/PartNavContainer.tsx
  src/features/ranking/apis.ts
  src/features/ranking/constants.ts
  src/features/ranking/queries.ts
  src/features/ranking/types.ts
  src/features/ranking/ui/BarrelContainerSkeleton.tsx
  src/features/ranking/ui/MyRank.tsx
  src/features/ranking/ui/MyRankSkeleton.tsx
  src/features/ranking/ui/RankingContainer.tsx
  src/features/ranking/ui/RankingItem.tsx
  src/features/ranking/ui/UserRankingList.tsx
  src/features/ranking/ui/UserRankingListSkeleton.tsx
  src/features/ranking/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/types.ts
  src/pages/ranking/Ranking.tsx
  src/pages/ranking/styles.ts
  src/style/animations.ts
  src/utils/generatePaginationPages.ts
Labels: ✨ Feature, 📬 API

#145 랭킹 페이지 로그인 후 새로고침 시 발생하는 버그 해결
  src/features/ranking/ui/MyRank.tsx
  src/features/user/queries.ts
Labels: 🐞 BugFix

#147 소개 페이지
  index.html
  src/common/ui/HeaderItem.tsx
  src/features/intro/constants.ts
  src/features/intro/service/hooks.ts
  src/features/intro/service/utils.ts
  src/features/intro/types.d.ts
  src/features/intro/ui/BadgeIntro.tsx
  src/features/intro/ui/FocusedItem.tsx
  src/features/intro/ui/PageIntroBanner.tsx
  src/features/intro/ui/QuizTutorial.tsx
  src/features/intro/ui/TutorialClear.tsx
  src/features/intro/ui/TutorialContainer.tsx
  src/features/intro/ui/TutorialHeader.tsx
  src/features/intro/ui/styles.ts
  src/features/quiz/hocs/withQuizzes.tsx
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/OXSelector.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/ShortAnswer.tsx
  src/features/tutorial/ui/styles.ts
  src/features/user/ui/AttendanceCalendar.tsx
  src/pages/intro/Intro.tsx
  src/pages/intro/styles.ts
  src/pages/login/LoginPage.tsx
  src/pages/quiz/tutorial/QuizTutorial.tsx
  src/route/Router.tsx
  src/store/useRectStore.ts
  src/style/animations.ts
Labels: 🎨 Publish, ✨ Feature

#148 랭킹 페이지 반응형 (모바일) 작업
  src/features/ranking/constants.ts
  src/features/ranking/types.ts
  src/features/ranking/ui/BarrelContainerSkeleton.tsx
  src/features/ranking/ui/RankingItem.tsx
  src/features/ranking/ui/UserRankingList.tsx
  src/features/ranking/ui/styles.ts
  src/features/user/types.ts
  src/pages/ranking/Ranking.tsx
  src/pages/ranking/styles.ts
Labels: 🎨 Publish

#152 출석체크 애니메이션 추가
  src/features/store/ui/styles.ts
  src/features/user/ui/AttendanceCalendar.tsx
  src/features/user/ui/styles.ts
  src/style/animations.ts
Labels: ✨ Feature

#150 유저의 Daily quest (일일 퀘스트) 조회
  src/features/quest/types.d.ts
  src/features/quest/types.ts
  src/features/quest/ui/DailyQuest.tsx
  src/features/quest/ui/MainQuest.tsx
  src/features/quest/ui/QuestSection.tsx
  src/features/quest/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
Labels: ✨ Feature, 📬 API

#153 Learn(학습) 튜토리얼 페이지
  src/common/layout/Modal.tsx
  src/features/intro/constants.ts
  src/features/intro/service/hooks.ts
  src/features/intro/service/utils.ts
  src/features/intro/ui/BadgeIntro.tsx
  src/features/intro/ui/FocusedItem.tsx
  src/features/intro/ui/LearnTutorial.tsx
  src/features/intro/ui/LearnTutorialContainer.tsx
  src/features/intro/ui/QuizTutorial.tsx
  src/features/intro/ui/QuizTutorialClear.tsx
  src/features/intro/ui/QuizTutorialContainer.tsx
  src/features/intro/ui/TutorialPromptModal.tsx
  src/features/intro/ui/styles.ts
  src/features/learn/apis.ts
  src/features/learn/queries.ts
  src/features/learn/types.ts
  src/features/learn/ui/LearnContainer.tsx
  src/features/learn/ui/PartItem.tsx
  src/features/learn/ui/PartNavContainer.tsx
  src/features/learn/ui/SectionNavigateContainer.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/quest/ui/DailyQuest.tsx
  src/features/ranking/ui/styles.ts
  src/hooks/useModal.ts
  src/hooks/useRenderDescription.ts
  src/pages/intro/Intro.tsx
  src/pages/learn/Learn.tsx
  src/pages/learn/styles.ts
  src/pages/learn/tutorial/LearnTutorialPage.tsx
  src/pages/quiz/tutorial/QuizTutorialPage.tsx
  src/route/Router.tsx
Labels: 🎨 Publish, ✨ Feature

#155 404 Not Found 페이지 반응형 (모바일)
  public/sitemap.xml
  src/features/error/ui/NotFound.tsx
  src/features/error/ui/styles.ts
Labels: 🎨 Publish

#158 스타일 관련 상수 파일(constants.ts)로 관리
  src/common/layout/Modal.tsx
  src/common/layout/Overlay.tsx
  src/common/layout/styles.ts
  src/common/types.d.ts
  src/common/ui/styles.ts
  src/features/error/ui/NotFound.tsx
  src/features/error/ui/styles.ts
  src/features/intro/service/utils.ts
  src/features/intro/ui/FocusedItem.tsx
  src/features/intro/ui/styles.ts
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/quest/ui/styles.ts
  src/features/quiz/ui/styles.ts
  src/features/ranking/ui/styles.ts
  src/features/user/ui/styles.ts
  src/pages/intro/styles.ts
  src/pages/learn/styles.ts
  src/pages/ranking/styles.ts
  src/style/constants.ts
  src/style/media.ts
  src/style/mediaQueryMap.ts
Labels: 🔨 Refactor

#159 퀘스트 페이지 반응형 (모바일)
  src/common/layout/MenuBar.tsx
  src/common/ui/styles.ts
  src/features/quest/ui/styles.ts
  src/features/user/ui/AttendanceCalendar.tsx
  src/pages/quest/styles.ts
Labels: 🎨 Publish

#162 생명력 sse 로직 추가
  src/App.tsx
  src/common/layout/SSEProvider.tsx
  src/features/user/apis.ts
  src/features/user/constants.ts
  src/features/user/hooks.ts
  src/features/user/queries.ts
  src/features/user/service/utils.ts
  src/features/user/ui/AttendanceCalendar.tsx
Labels: ✨ Feature, 📝 Modify

#165 quiz 페이지 ui 수정
  src/features/intro/ui/QuizTutorialContainer.tsx
  src/features/quiz/stores.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/OXSelector.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/QuizContainer.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/ShortAnswer.tsx
  src/features/quiz/ui/TextBlock.tsx
  src/features/quiz/ui/styles.css
  src/features/quiz/ui/styles.ts
  src/features/quiz/utils.ts
  src/features/user/ui/TotalResults.tsx
  src/store/useClientQuizStore.ts
  src/store/useDnDStore.ts
Labels: ✨ Feature, 🔨 Refactor

#164 로드되지 않은 섹션 선택 시 이동 불가 버그 수정
  src/features/intro/constants.ts
  src/features/intro/ui/LearnTutorialContainer.tsx
  src/features/learn/constants.ts
  src/features/learn/types.d.ts
  src/features/learn/ui/LearnContainer.tsx
  src/features/learn/ui/SectionNavigateContainer.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/user/queries.ts
Labels: 🐞 BugFix

#167 소개 페이지 반응형
  src/features/intro/ui/PageIntroBanner.tsx
  src/features/intro/ui/styles.ts
  src/pages/intro/Intro.tsx
  src/pages/intro/styles.ts
Labels: 🎨 Publish

#169 이용약관 페이지, 생명력 버그 수정
  src/features/quiz/ui/QuizContainer.tsx
  src/features/user/hooks.ts
  src/features/user/queries.ts
  src/pages/intro/Intro.tsx
  src/pages/intro/styles.ts
  src/pages/terms-of-service/TermsOfService.tsx
  src/pages/terms-of-service/styles.ts
  src/route/Router.tsx
Labels: 🎨 Publish, 🐞 BugFix

#172 npm → yarn berry 마이그레이션
  .gitignore
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  Dockerfile
  package-lock.json
  package.json
  yarn.lock
Labels: ⚙ Setting

#175 yarn berry node_modules → PnP 마이그레이션
  .dockerignore
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  .vscode/extensions.json
  .yarn/install-state.gz
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  vite.config.ts
  yarn.lock
Labels: ⚙ Setting, 🌏 Deploy

#176 문의하기 추가
  .pnp.cjs
  .yarn/install-state.gz
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/types/index.d.ts
  .yarn/sdks/eslint/lib/types/rules/index.d.ts
  .yarn/sdks/eslint/lib/types/universal.d.ts
  .yarn/sdks/eslint/lib/types/use-at-your-own-risk.d.ts
  .yarn/sdks/eslint/lib/universal.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  eslint.config.js
  package-lock.json
  package.json
  src/common/layout/HeaderItemContainer.tsx
  src/features/quiz/ui/QuizContainer.tsx
  src/features/quiz/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/constants.ts
  src/features/user/queries.ts
  src/features/user/types.ts
  src/features/user/ui/OpinionsModal.tsx
  src/features/user/ui/OpinionsModalTrigger.tsx
  src/features/user/ui/styles.ts
  src/pages/learn/styles.ts
  src/pages/profile/Profile.tsx
  src/pages/profile/styles.ts
  src/style/constants.ts
  yarn.lock
Labels: ✨ Feature

#180 튜토리얼 관련 모달 스타일
  .gitignore
  .yarn/install-state.gz
  package-lock.json
  src/features/intro/ui/QuizTutorialClear.tsx
  src/features/intro/ui/TutorialPromptModal.tsx
  src/features/intro/ui/styles.ts
Labels: 🎨 Publish

#183 파트 클리어 시 파트 이름 뜨기 추가
  .pnp.cjs
  .yarn/sdks/typescript/package.json
  package.json
  src/features/quiz/apis.ts
  src/features/quiz/hocs/withQuizzes.tsx
  src/features/quiz/queries.ts
  src/features/quiz/types.d.ts
  src/features/user/service/authUtils.ts
  src/features/user/ui/PartClear.tsx
  yarn.lock
Labels: ✨ Feature

#186 문의, 출첵 아이콘 수정
  src/features/intro/ui/QuizTutorialContainer.tsx
  src/features/intro/ui/TutorialPromptModal.tsx
  src/features/user/ui/AttendanceCalendarModal.tsx
  src/features/user/ui/OpinionsModalTrigger.tsx
  src/features/user/ui/styles.ts
Labels: 🔨 Refactor

#188 상점1
  src/common/layout/Header.tsx
  src/common/layout/Overlay.tsx
  src/common/layout/styles.ts
  src/common/ui/styles.ts
  src/features/error/ui/ItemFallback.tsx
  src/features/learn/hocs/withSections.tsx
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/styles.ts
  src/features/store/apis.ts
  src/features/store/constants.ts
  src/features/store/hocs/withCosmeticItem.tsx
  src/features/store/queries.ts
  src/features/store/store.ts
  src/features/store/types.d.ts
  src/features/store/types.ts
  src/features/store/ui/CartList.tsx
  src/features/store/ui/CosmeticItemCheckOut.tsx
  src/features/store/ui/ItemContainer.tsx
  src/features/store/ui/ItemSkeleton.tsx
  src/features/store/ui/PageNavBar.tsx
  src/features/store/ui/PreviewMyCharacter.tsx
  src/features/store/ui/PreviewMyProfileImage.tsx
  src/features/store/ui/PurchaseModal.tsx
  src/features/store/ui/StoreItem.tsx
  src/features/store/ui/StoreSortBar.tsx
  src/features/store/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/ui/MyCharacter.tsx
  src/features/user/ui/ProfileImage.tsx
  src/features/user/ui/StoreMyCharacterSection.tsx
  src/features/user/ui/TotalResults.tsx
  src/features/user/ui/styles.ts
  src/pages/store/Store.tsx
  src/pages/store/styles.ts
  src/types.d.ts
  src/utils/compact.ts
Labels: ✨ Feature
