Repository modern-agile-team/8term-coko-Front, pull requests merged in 2025-01, with the labels that each got.

#99 퀘스트 페이지 퍼블리싱
  src/features/learn/style.ts
  src/features/progress/style.ts
  src/features/progress/ui/ProgressBar.tsx
  src/features/quest/style.ts
  src/features/quest/types.ts
  src/features/quest/ui/DailyQuest.tsx
  src/features/quest/ui/MainQuest.tsx
  src/features/quest/ui/MainQuset.tsx
  src/features/quest/ui/QuestSection.tsx
  src/features/quest/ui/styles.ts
  src/pages/quest/Quest.tsx
  src/pages/quest/styles.ts
  tsconfig.app.json
Labels: 🎨 Publish

#98 파트 진행도 업데이트 로직 추가
  src/features/quiz/apis.ts
  src/features/quiz/constants.ts
  src/features/quiz/queries.ts
  src/features/quiz/service/addLineNumbersToCode.ts
  src/features/quiz/service/hooks.ts
  src/features/quiz/service/quizUtils.ts
  src/features/quiz/service/replaceEmptyWithHTMLElement.ts
  src/features/quiz/types.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/constants.ts
  src/features/user/queries.ts
  src/features/user/service/authUtils.ts
  src/features/user/ui/PartClear.tsx
  src/features/user/ui/TotalResults.tsx
  src/pages/learn/Learn.tsx
  src/pages/quiz/Quiz.tsx
  src/store/useClientQuizStore.ts
  src/store/useUserStore.ts
Labels: ✨ Feature, 🔨 Refactor

#105 seo 최적화(간단한)
  .github/issue-branch.yml
  .github/workflows/ci-cd.yml
  index.html
  package-lock.json
  public/robots.txt
  public/sitemap.xml
  src/App.tsx
  src/axios/instance.ts
  src/axios/interceptor.ts
  src/common/layout/Header.tsx
  src/common/ui/style.ts
  src/features/auth/apis.ts
  src/features/auth/queries.ts
  src/features/auth/service/handleLogin.ts
  src/features/auth/service/handleLogout.ts
  src/features/auth/ui/Login.tsx
  src/features/auth/ui/LoginPrompt.tsx
  src/features/auth/ui/styles.ts
  src/features/learn/apis.ts
  src/features/learn/constants.ts
  src/features/learn/queries.ts
  src/features/learn/types.ts
  src/features/learn/ui/KeycapAdventureIntro.tsx
  src/features/learn/ui/NavigationControl.tsx
  src/features/learn/ui/SectionArrowButton.tsx
  src/features/learn/ui/SectionNavigateContainer.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/login/service/handleLogin.ts
  src/features/login/service/handleLogout.ts
  src/features/quiz/service/quizUtils.ts
  src/features/quiz/types.ts
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/Result.tsx
  src/features/ranking/ui/MyRank.tsx
  src/features/ranking/ui/RankingContainer.tsx
  src/features/user/apis.ts
  src/features/user/types.ts
  src/features/user/ui/TotalResults.tsx
  src/hooks/usePopover.ts
  src/pages/learn/Learn.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/ranking/Ranking.tsx
  src/store/useUserStore.ts
  src/utils/.gitkeep
  src/utils/cookies.ts
  src/utils/formatDate.ts
  src/utils/isLoggedIn.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🌏 Deploy

#104 에러 바운더리, 서스펜스를 사용한 통합 에러 핸들링
  package-lock.json
  package.json
  src/App.tsx
  src/common/layout/Loader.tsx
  src/common/layout/style.ts
  src/features/error/constants.ts
  src/features/error/service/errorUtils.ts
  src/features/error/ui/Fallback.tsx
  src/features/error/ui/NotFound.tsx
  src/features/error/ui/QueryErrorBoundary.tsx
  src/features/error/ui/styles.ts
  src/features/quiz/queries.ts
  src/features/user/queries.ts
  src/pages/quiz/Quiz.tsx
  src/route/Router.tsx
Labels: ✨ Feature

#106 Section, Part (User 관련 작업 포함) 작업1
  .github/workflows/ci-cd.yml
  src/axios/interceptor.ts
  src/axios/statusCode.ts
  src/common/layout/Header.tsx
  src/common/layout/Loader.tsx
  src/features/auth/apis.ts
  src/features/auth/queries.ts
  src/features/error/ui/Fallback.tsx
  src/features/learn/constants.ts
  src/features/learn/queries.ts
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/quiz/constants.ts
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/styles.ts
  src/pages/learn/Learn.tsx
  src/store/useClientQuizStore.ts
  src/store/useDnDStore.ts
  src/store/useUserStore.ts
Labels: ✨ Feature

#109 dependencies 패키지 버전 최신화
  Dockerfile
  package-lock.json
  package.json
  src/hooks/useFunnel.tsx
  src/hooks/useOutsideClick.ts
  src/hooks/usePopover.ts
  src/main.tsx
  src/utils/componentMap.tsx
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ⚙ Setting

#111 CI/CD 워크플로우 및 Docker 액션 최신화
  .github/workflows/ci-cd.yml
  Dockerfile
  default.conf.template
  src/main.tsx
Labels: 🌏 Deploy

#101 SortDropdown 범용적 컴포넌트로 변경
  .github/workflows/ci-cd.yml
  src/common/layout/CokoLogo.tsx
  src/common/layout/Header.tsx
  src/common/layout/Loader.tsx
  src/common/layout/MenuBar.tsx
  src/common/layout/Modal.tsx
  src/common/layout/SortDropdown.tsx
  src/common/layout/constants.ts
  src/common/layout/style.ts
  src/common/layout/styles.ts
  src/features/ranking/constants.ts
  src/features/ranking/ui/MyRank.tsx
  src/features/ranking/ui/RankingContainer.tsx
  src/features/ranking/ui/SortDropdown.tsx
  src/features/ranking/ui/styles.ts
  src/pages/learn/Learn.tsx
  src/pages/profile/Profile.tsx
  src/pages/quest/Quest.tsx
  src/pages/ranking/Ranking.tsx
  src/pages/store/Store.tsx
Labels: 📝 Modify

#113 Header 뒤로가기 버튼 추가 및 클릭 시 모달 생성
  src/App.tsx
  src/common/layout/GoBackPrompt.tsx
  src/common/layout/Header.tsx
  src/common/layout/MenuBar.tsx
  src/common/layout/styles.ts
  src/common/ui/GoBackButton.tsx
  src/common/ui/HeaderItem.tsx
  src/common/ui/MenuItem.tsx
  src/common/ui/styles.ts
  src/features/auth/queries.ts
  src/features/auth/ui/Login.tsx
  src/features/learn/ui/styles.ts
  src/features/progress/styles.ts
  src/features/progress/ui/ProgressBar.tsx
  src/features/quest/ui/styles.ts
  src/features/quiz/ui/styles.ts
  src/features/user/queries.ts
  src/features/user/ui/PartClear.tsx
  src/hooks/useUserInitializer.ts
  src/main.tsx
  src/pages/learn/Learn.tsx
  src/pages/learn/styles.ts
  src/pages/profile/Profile.tsx
  src/pages/quest/Quest.tsx
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/styles.ts
  src/pages/ranking/Ranking.tsx
  src/pages/store/Store.tsx
  src/route/Router.tsx
  src/store/useClientQuizStore.ts
  src/style/LayOut.ts
  src/style/animations.ts
  src/style/media.ts
  src/style/styles.ts
  src/types/LayOut.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
Labels: ✨ Feature

#116 MenuBar 모바일 반응형 작업
  src/common/layout/MenuBar.tsx
  src/common/layout/styles.ts
  src/common/ui/MenuItem.tsx
  src/common/ui/styles.ts
  src/features/learn/ui/KeycapAdventureIntro.tsx
  src/features/quest/ui/DailyQuest.tsx
  src/features/quest/ui/MainQuest.tsx
  src/features/quest/ui/QuestSection.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/styles.ts
  src/pages/learn/Learn.tsx
  src/pages/learn/styles.ts
Labels: 🎨 Publish

#115 퀴즈 튜토리얼 기능 추가
  .gitignore
  index.html
  package-lock.json
  src/App.tsx
  src/common/layout/Modal.tsx
  src/common/layout/OverRay.tsx
  src/common/layout/styles.ts
  src/common/types.d.ts
  src/common/ui/HeaderItem.tsx
  src/features/error/ui/NotFound.tsx
  src/features/error/ui/QuizErrorBoundary.tsx
  src/features/learn/types.ts
  src/features/quiz/hocs/withQuizzes.tsx
  src/features/quiz/service/hooks.ts
  src/features/quiz/types.ts
  src/features/quiz/ui/Combination.tsx
  src/features/quiz/ui/MultipleChoice.tsx
  src/features/quiz/ui/OXSelector.tsx
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/QuizContainer.tsx
  src/features/quiz/ui/QuizSection.tsx
  src/features/quiz/ui/ShortAnswer.tsx
  src/features/quiz/ui/styles.ts
  src/features/tutorial/constants.ts
  src/features/tutorial/service/hooks.ts
  src/features/tutorial/service/utils.ts
  src/features/tutorial/types.d.ts
  src/features/tutorial/ui/FocusedItem.tsx
  src/features/tutorial/ui/QuizTutorial.tsx
  src/features/tutorial/ui/TutorialClear.tsx
  src/features/tutorial/ui/TutorialContainer.tsx
  src/features/tutorial/ui/TutorialHeader.tsx
  src/features/tutorial/ui/styles.ts
  src/hooks/useFunnel.tsx
  src/hooks/useModal.ts
  src/pages/learn/Learn.tsx
  src/pages/learn/styles.ts
  src/pages/quiz/Quiz.tsx
  src/pages/quiz/tutorial/QuizTutorial.tsx
  src/route/Router.tsx
  src/store/useClientQuizStore.ts
  src/store/useRectStore.ts
  src/utils/componentMap.tsx
  src/utils/getImageNameFromUrl.ts
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: ✨ Feature

#119 Learn 페이지 반응형(모바일) 작업
  src/App.tsx
  src/common/ui/styles.ts
  src/features/error/ui/NotFound.tsx
  src/features/learn/constants.ts
  src/features/learn/types.ts
  src/features/learn/ui/NavigationControl.tsx
  src/features/learn/ui/SectionNavigateContainer.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/learn/ui/styles.ts
  src/features/quiz/ui/PartNavContainer.tsx
  src/features/quiz/ui/styles.ts
  src/pages/learn/Learn.tsx
  src/pages/learn/styles.ts
  src/pages/ranking/styles.ts
  src/style/animations.ts
  src/style/mediaQueryMap.ts
Labels: 🎨 Publish

#122 api 수정
  src/axios/interceptor.ts
  src/features/quiz/hocs/withQuizzes.tsx
  src/features/quiz/ui/QuizContainer.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/ui/styles.ts
  src/features/tutorial/ui/TutorialContainer.tsx
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/ui/PartClear.tsx
  src/features/user/ui/TotalResults.tsx
  src/pages/quiz/styles.ts
Labels: 📬 API, 🐞 BugFix, 📝 Modify

#123 생명력 감소 로직 추가
  src/common/layout/Header.tsx
  src/common/layout/UserPresentHeaderItemContainer.tsx
  src/features/error/ui/HeaderErrorBoundary.tsx
  src/features/quiz/hooks.ts
  src/features/quiz/ui/Question.tsx
  src/features/quiz/ui/Result.tsx
  src/features/quiz/utils.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/types.ts
  src/features/user/ui/TotalResults.tsx
  src/pages/quiz/Quiz.tsx
Labels: ✨ Feature
