Repository modern-agile-team/8term-coko-Front, pull requests merged in 2025-03, with the labels that each got.

#192 사용자의 파트 상태에 따라 정답 상태 업데이트 로직 개선
  src/features/quiz/ui/Result.tsx
  src/features/user/constants.ts
  src/features/user/ui/OpinionsModal.tsx
Labels: 📝 Modify

#195 상점 기능추가및 기능추가
  .pnp.cjs
  src/common/layout/Header.tsx
  src/features/intro/ui/TutorialHeader.tsx
  src/features/profile/ui/LevelBar.tsx
  src/features/profile/ui/ProfileDetails.tsx
  src/features/profile/ui/styles.ts
  src/features/ranking/queries.ts
  src/features/ranking/types.d.ts
  src/features/ranking/ui/MyRank.tsx
  src/features/ranking/ui/RankingItem.tsx
  src/features/ranking/ui/UserRankingList.tsx
  src/features/ranking/ui/styles.ts
  src/features/store/constants.ts
  src/features/store/hocs/withCosmeticItem.tsx
  src/features/store/queries.ts
  src/features/store/types.d.ts
  src/features/store/ui/CartList.tsx
  src/features/store/ui/ItemContainer.tsx
  src/features/store/ui/PageNavBar.tsx
  src/features/store/ui/PreviewMyCharacter.tsx
  src/features/store/ui/PreviewMyProfileImage.tsx
  src/features/store/ui/PurchaseModal.tsx
  src/features/store/ui/StoreMyCharacterSection.tsx
  src/features/store/ui/StoreSortBar.tsx
  src/features/store/ui/styles.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/ui/MyCharacter.tsx
  src/features/user/ui/OpinionsModal.tsx
  src/features/user/ui/ProfileImage.tsx
  src/features/user/ui/TotalResults.tsx
  src/features/user/ui/styles.ts
  src/pages/creators/styles.ts
  src/pages/store/Store.tsx
  src/pages/store/styles.ts
  src/style/constants.ts
Labels: ✨ Feature

#198 설정 제거, 내 아이템 보기 버튼 수정
  src/common/layout/constants.ts
  src/features/ranking/queries.ts
  src/features/store/ui/StoreMyCharacterSection.tsx
  src/features/user/queries.ts
Labels: 🐞 BugFix

#200 userAttendanceQuery로 이름 변경 및 초기화 쿼리 수정
  src/features/user/queries.ts
  src/features/user/ui/AttendanceCalendar.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#202 만든사람들 페이지 이미지추가
  src/features/intro/constants.ts
  src/pages/creators/Creators.tsx
  src/pages/terms-of-service/TermsOfService.tsx
Labels: 🎨 Publish

#201 뱃지 로딩 중 스켈레톤 UI 표시
  .pnp.cjs
  .pnp.loader.mjs
  .yarnrc.yml
  package.json
  src/common/layout/Header.tsx
  src/common/layout/SSEProvider.tsx
  src/common/ui/styles.ts
  src/features/learn/hocs/withUserProgress.tsx
  src/features/learn/ui/SelectSection.tsx
  src/features/profile/ui/AuthRequiredNotice.tsx
  src/features/profile/ui/BadgeContainer.tsx
  src/features/profile/ui/BadgeContainerSkeleton.tsx
  src/features/profile/ui/ProfileDetails.tsx
  src/features/profile/ui/styles.ts
  src/features/quest/ui/ChallengeList.tsx
  src/features/quest/ui/ChallengeListContent.tsx
  src/features/quest/ui/ChallengeListContentSkeleton.tsx
  src/features/quest/ui/DailyQuest.tsx
  src/features/quiz/ui/Result.tsx
  src/features/ranking/constants.ts
  src/features/ranking/types.d.ts
  src/features/user/apis.ts
  src/features/user/queries.ts
  src/features/user/types.ts
  src/features/user/ui/BadgeContainer.tsx
  src/features/user/ui/styles.ts
  src/pages/profile/Profile.tsx
  src/pages/quest/Quest.tsx
  src/pages/ranking/Ranking.tsx
Labels: 📝 Modify

#206 google analytics추가
  .pnp.cjs
  index.html
  src/features/store/ui/ItemContainer.tsx
  src/features/store/utils.ts
  src/features/user/ui/styles.ts
Labels: 🔨 Refactor

#205 랭킹 카운트 다운 타이머 (랭킹 및 도전과제 관련)
  src/features/ranking/apis.ts
  src/features/ranking/queries.ts
  src/features/ranking/types.d.ts
  src/features/ranking/ui/RankingTimer.tsx
  src/features/ranking/ui/UserRankingList.tsx
  src/features/ranking/ui/styles.ts
Labels: ✨ Feature, 📬 API

#209 랭킹 타이머 즉시 문구 보이게 수정
  .pnp.cjs
  src/features/ranking/apis.ts
  src/features/ranking/queries.ts
  src/features/ranking/types.d.ts
  src/features/ranking/ui/RankingTimer.tsx
  src/features/ranking/ui/UserRankingList.tsx
  src/features/ranking/ui/styles.ts
Labels: 🐞 BugFix

#213 버그수정
  src/common/layout/SSEProvider.tsx
  src/features/ranking/queries.ts
  src/features/ranking/ui/RankingTimer.tsx
  src/features/store/store.ts
  src/features/store/ui/CartList.tsx
  src/features/store/ui/PurchaseModal.tsx
  src/pages/store/Store.tsx
Labels: 🐞 BugFix

#214 v1.0.1
  .pnp.cjs
  src/common/layout/SSEProvider.tsx
  src/features/store/store.ts
  src/features/store/ui/CartList.tsx
  src/features/store/ui/PurchaseModal.tsx
  src/pages/store/Store.tsx
Labels: 🐞 BugFix

#217 아이템 미리보기 버튼 기능 수정 및 페이지 초기화 기능 개선
  src/features/store/ui/StoreMyCharacterSection.tsx
Labels: 🐞 BugFix

#218 Bug fix/#215/instance separation
  .pnp.cjs
  package.json
  src/axios/interceptor.ts
  src/common/layout/Header.tsx
  src/features/auth/queries.ts
  src/features/auth/service/handleLogout.ts
  src/features/store/ui/StoreMyCharacterSection.tsx
  src/hooks/useUserInitializer.ts
  yarn.lock
Labels: 🐞 BugFix

#220 README.md 수정 및 개발 서버 배포
  .github/workflows/ci-cd.yml
  .github/workflows/dev-ci-cd.yml
  README.md
  dev-build.sh
Labels: 🌏 Deploy, 📝 Modify

#221 1.0.2
  .github/workflows/ci-cd.yml
  .github/workflows/dev-ci-cd.yml
  .pnp.cjs
  README.md
  dev-build.sh
  package.json
  src/axios/interceptor.ts
  src/common/layout/Header.tsx
  src/features/auth/queries.ts
  src/features/auth/service/handleLogout.ts
  src/features/store/ui/StoreMyCharacterSection.tsx
  src/hooks/useUserInitializer.ts
  yarn.lock
Labels: ⚙ Setting, 🌏 Deploy

#223 Setting/#222/resolve dependabot security alerts
  .pnp.cjs
  package.json
  yarn.lock
Labels: 🌏 Deploy, 🐞 BugFix
